import random
import requests
import io
from django.core.management.base import BaseCommand
from django.contrib.auth.hashers import make_password
from django.core.files.base import ContentFile
from faker import Faker

from docx import Document
from pptx import Presentation

from core.models import User
from categories.models import Category
from notes.models import Note, Tag, Rating

class Command(BaseCommand):
    help = 'Seeds the database with 50 notes (PDF, DOCX, PPTX) and other dummy data.'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.SUCCESS('Starting "Villain Arc" data seed v3 (Optimized)... 😈'))

        # 0. Clean database
        self.stdout.write('Cleaning old data...')
        Rating.objects.all().delete()
        Note.objects.all().delete()
        Tag.objects.all().delete()
        Category.objects.all().delete()
        User.objects.filter(is_superuser=False).delete()

        fake = Faker()

        # 1. Create Users
        self.stdout.write('Creating users...')
        try:
            admin_user = User.objects.get(is_superuser=True)
            admin_user.first_name = "Admin"
            admin_user.last_name = "User"
            admin_user.reputation = 999
            admin_user.save()
        except User.DoesNotExist:
            self.stdout.write(self.style.ERROR('Superuser not found! Please create one first with `python manage.py createsuperuser`'))
            return

        student_user = User.objects.create(username='student', password=make_password('password123'), first_name='Student', last_name='User', email='student@example.com', role='student', is_active=True)
        teacher_user = User.objects.create(username='teacher', password=make_password('password123'), first_name='Teacher', last_name='User', email='teacher@example.com', role='teacher', is_active=True, is_staff=True)
        
        users = [admin_user, student_user, teacher_user]
        for _ in range(10):
            users.append(User.objects.create(username=fake.user_name(), password=make_password('password123'), first_name=fake.first_name(), last_name=fake.last_name(), email=fake.email(), role=random.choice(['student', 'teacher']), is_active=True))

        # 2. Create Categories
        self.stdout.write('Creating categories...')
        category_names = ['Data Structures', 'Algorithms', 'Web Development', 'Operating Systems', 'Machine Learning', 'Database Systems', 'Software Engineering', 'Networking']
        categories = [Category.objects.create(name=name) for name in category_names]

        # 3. Create Tags
        self.stdout.write('Creating tags...')
        tag_names = ['python', 'dsa', 'sem4', 'important', 'exam-prep', 'quick-ref', 'javascript', 'react', 'django', 'ai', 'sql', 'project']
        tags = [Tag.objects.get_or_create(name=name)[0] for name in tag_names]

        # 4. Generate 3 Dummy File Payloads
        self.stdout.write('Generating dummy file payloads (PDF, DOCX, PPTX)...')
        dummy_files = {}

        # PDF
        try:
            pdf_url = "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
            response = requests.get(pdf_url)
            response.raise_for_status() 
            dummy_files['pdf'] = ContentFile(response.content, name="dummy.pdf")
            self.stdout.write(self.style.SUCCESS('...Dummy PDF downloaded.'))
        except requests.exceptions.RequestException as e:
            self.stdout.write(self.style.ERROR(f'Could not download dummy PDF: {e}'))
            dummy_files['pdf'] = None

        # DOCX
        try:
            docx_buffer = io.BytesIO()
            doc = Document()
            doc.add_heading('EduShare Dummy DOCX', 0)
            doc.add_paragraph('This is a dummy .docx file generated by the "Villain Arc" seeder.')
            doc.save(docx_buffer)
            dummy_files['docx'] = ContentFile(docx_buffer.getvalue(), name="dummy.docx")
            self.stdout.write(self.style.SUCCESS('...Dummy DOCX generated.'))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Could not create dummy DOCX: {e}'))
            dummy_files['docx'] = None

        # PPTX
        try:
            pptx_buffer = io.BytesIO()
            prs = Presentation()
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = "EduShare Dummy PPTX"
            slide.placeholders[1].text = 'Generated by the "Villain Arc" seeder.'
            prs.save(pptx_buffer)
            dummy_files['pptx'] = ContentFile(pptx_buffer.getvalue(), name="dummy.pptx")
            self.stdout.write(self.style.SUCCESS('...Dummy PPTX generated.'))
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Could not create dummy PPTX: {e}'))
            dummy_files['pptx'] = None

        # 5. Create 50 Notes
        self.stdout.write('Creating 50 dummy notes with random file types...')
        all_notes = []
        for i in range(10):
            uploader = random.choice(users)
            note = Note(
                title=f"Note {i+1}: {fake.sentence(nb_words=3).replace('.', '')}",
                description=fake.paragraph(nb_sentences=5),
                uploader=uploader,
                category=random.choice(categories),
                is_public=True
            )
            note.save() 
            
            # --- MEMORY LEAK FIX ---
            file_type = random.choice(['pdf', 'docx', 'pptx'])
            dummy_file = dummy_files.get(file_type)
            if dummy_file:
                # 1. Reset the file pointer
                dummy_file.seek(0)
                # 2. Save using the *original* ContentFile object, not a new copy
                note.file.save(f"dummy_note_{i+1}.{file_type}", dummy_file, save=True)
            # --- END FIX ---

            note.tags.set(random.sample(tags, random.randint(1, 3)))
            
            uploader.reputation += 10
            uploader.save()
            all_notes.append(note)

        # 6. Create Ratings
        self.stdout.write('Creating ratings and calculating reputation...')
        for note in all_notes:
            num_ratings = random.randint(3, 10)
            raters = random.sample(users, num_ratings)
            
            for rater in raters:
                if rater == note.uploader:
                    continue
                
                rating_value = random.randint(1, 5)
                Rating.objects.create(note=note, user=rater, value=rating_value)
                
                if rating_value >= 4:
                    note.uploader.reputation += 5 
                elif rating_value <= 2:
                    note.uploader.reputation -= 2
                note.uploader.save()
            
            note.update_rating()

        self.stdout.write(self.style.SUCCESS('----------------------------------'))
        self.stdout.write(self.style.SUCCESS('"Villain Arc" Seed v3 Complete! 😈'))
        self.stdout.write(self.style.SUCCESS('Database is now full and memory leak is fixed.'))